import json,subprocess
from pathlib import Path
r=Path('C:/audio/shared/amtw-runtime/jobs/monsters-loose-word-timing-20260913');preview='animatic/MonstersLoose-v93-swamp-cousin-beacons.mp4'
probe=json.loads(subprocess.check_output(['ffprobe','-v','error','-show_streams','-of','json',str(r/preview)]))
v=next(s for s in probe['streams'] if s['codec_type']=='video');assert int(v['nb_frames'])==5290 and v['r_frame_rate']=='24/1';assert any(s['codec_type']=='audio' for s in probe['streams'])
p=r/'shots/shotlist.json';d=json.loads(p.read_text())
for s in d['shots']:
 if s['start_frame']>=4414 and s['id']!='SCN-015-FINALE':s['status']='user_approved_performance'
 effect='motion-graphics/OUTRO-LIGHTS-001/'+s['id']+'-beacons-v001.mp4'
 if not (r/effect).exists():continue
 s['pre_beacon_source']=s['source'];s.update(source=effect,source_in_frame=0,effects_status='tracked_red_beacons_for_review',beacon_record='motion-graphics/OUTRO-LIGHTS-001/'+s['id']+'-tracks.json')
 if s['id']=='SCN-015-FINALE':
  s.update(status='regenerated_for_review',generation_record='video-tests/KLING-SCENE14-FINALE-003/request.json',original_video_source='video-tests/KLING-SCENE14-FINALE-003/KLING-SCENE14-FINALE-003-01.mp4',native_source_in_frame=12,native_source_end_frame_exclusive=352,actual_leading_handle_frames=12,actual_trailing_handle_frames=9,starting_image='assets/SCN-015-FINALE-v002.png',direction_record='video-tests/KLING-SCENE14-FINALE-003/request.json',effects_record='motion-graphics/OUTRO-LIGHTS-001/review.md')
d['current_preview']=preview;d['next_scene_planning']['preview']=preview;d['ending_planning'].update(preview=preview,status='revised_finale_and_beacons_for_review',credits_consumed=728,outro_credits_consumed=648,latest_regeneration_credits=240,rejected_take='video-tests/KLING-SCENE14-FINALE-002/review.json')
p.write_text(json.dumps(d,indent=2)+'\n')
p=Path('projects/monsters-loose/README.md');text=p.read_text(encoding='utf-8').replace('Current preview: **v92**','Current preview: **v93**').replace('recovery/animatic/MonstersLoose-v92-outro-performances.blend','recovery/animatic/MonstersLoose-v93-swamp-cousin-beacons.blend').replace('Open the current v92 Blender','Open the current v93 Blender');p.write_text('Latest v93: finale4951..5290 regenerated with established mossy swamp cousin in revised starting frame, stronger gentle crane up/back.240additional credits. Tracked red beacon pass across exit/outro; existing good blinking retained. Top scene titles and narrative markers removed throughout; bottom lyrics and countdown graphics preserved. Earlier v92 performances approved. Review finale from4940; light pass from3883.\n\n'+text,encoding='utf-8')
Path('projects/monsters-loose/HANDOFF.md').write_text('# Current working state\n\nPreview v93: MonstersLoose-v93-swamp-cousin-beacons.mp4/.blend,5290frames24fps. User approved v92 except style-mismatched emerging water creature. Finale now regenerated using mossy swamp cousin identity in revised starting frame and more crane up/back,240additional Kling credits. Source take003, zero-based12..352 used for master4951..5291 exclusive. Normal12frame lead-in retained.\n\nRed beacon pass covers visible steady architectural lamps in exit3883, swamp meeting4242, CEO4414, play4624, inspector4719, Harper/kid4793 and finale4951. Existing generated blinking in corridor4126 and boss appraisal4465 retained. Other shots have no visible red structural beacons. Effects are localized, tracked and29frame cadence matching earlier lamps. Reproduce with motion-graphics/outro-lights.py then animatic/build-opening-v93.py; explicit tracked finale coordinates in OUTRO-LIGHTS-001/finale-anchors.json. Generation request and source in KLING-SCENE14-FINALE-003. Rejected original and scene-switching take002 preserved.\n\nScene-marker/title and narrative text removed throughout; bottom lyrics and countdown graphics preserved. See animatic/v93-removed-scene-markers.json for exact removals. Review pending on these changes. Earlier kid eye-roll and cutesy Harper YES WAY remain deferred. Large media remains external to Git.\n')
p=r/'animatic/frame-review-current.json';tmp=p.with_suffix('.tmp');tmp.write_text(json.dumps(dict(video=str(r/preview),master_start=1)));tmp.replace(p)
print('v93 published;5290frames;240additional credits')
