from pathlib import Path
import json
r=Path('C:/audio/shared/amtw-runtime/jobs/monsters-loose-word-timing-20260913');p=r/'shots/shotlist.json';d=json.loads(p.read_text());preview='animatic/MonstersLoose-v80-vapor-cyclops.mp4'
for s in d['shots']:
 if s['id']=='SCN-011-SMOKE-B':
  s.update(source='motion-graphics/SCENE11-SMOKE-002/smoke-b-timed-v001.mp4',status='retake_assembled_for_review',effects_record='motion-graphics/SCENE11-SMOKE-002/selections.json',generation_record='video-tests/KLING-SCENE11-SMOKE-B-002/request.json',note='Kling Element321906902305573 binds original Cyclops portrait and pre-transformation reference. Source4..96 into51frames; smoke expands and reveals familiar creature, cut before final solid settling.')
  s.pop('review_concern',None)
d['current_preview']=preview;d['next_scene_planning'].update(preview=preview,status='first_five_approved_reference_bound_smoke_retake_for_review',credits=280);d['next_scene_planning'].pop('review_concern',None);p.write_text(json.dumps(d,indent=2)+'\n')
p=r/'animatic/frame-review-current.json';t=p.with_suffix('.tmp');t.write_text(json.dumps(dict(video=str(r/preview),master_start=1)));t.replace(p)
p=Path('projects/monsters-loose/README.md');s=p.read_text(encoding='utf-8').replace('Current preview: **v79**','Current preview: **v80**').replace('recovery/animatic/MonstersLoose-v79-transformations.blend','recovery/animatic/MonstersLoose-v80-vapor-cyclops.blend').replace('Open the current v79 Blender','Open the current v80 Blender');p.write_text('Latest v80: first five Scene11 takes user-approved and untouched. Replaced final smoke emergence with take002 using character Element321906902305573, original portrait + interior start. Growing cloud reveals recognizable Cyclops; source4..96 selected before solid end.40additional credits, Scene11 total280. Review3690 for transition.\n\n'+s,encoding='utf-8')
p=r/'shots/SCN-011-transformations-shot-plan.md';p.write_text(p.read_text(encoding='utf-8')+'\n\n## v80 smoke retake\nUser approved first five shots; rejected SMOKE-B001 identity. Retake002 uses Kling character Element321906902305573 (SCN-007-exobiology-v003 and SCN-011-SMOKE-A-v001), not end-frame conditioning. Expanding smoke reveals recognizable Cyclops. Source4..96 in51frames ends partly veiled, before later solid settling.40additional credits,280scene total. No changes to first five.\n',encoding='utf-8')
