from pathlib import Path
import json
r=Path('C:/audio/shared/amtw-runtime/jobs/monsters-loose-word-timing-20260913');p=r/'shots/shotlist.json';d=json.loads(p.read_text());preview='animatic/MonstersLoose-v78-transformation-starts.mp4'
d['scene11_previous_storyboards']=[s for s in d['shots'] if s['id'].startswith('SCN-011')];d['shots']=[s for s in d['shots'] if not s['id'].startswith('SCN-011')]
proposal=json.loads((r/'shots/SCN-011-six-shot-proposal.json').read_text())
for s in proposal['shots']:
 name=s['id'].replace('SCN-011-','');s['status']='starting_frame_for_review';s['source']=f'assets/SCN-011-{name}-v001.png'
 if name=='SMOKE-A':s['starting_frame']='Established translucent lavender space-octopus Cyclops with ONE oversized eye and amber/turquoise organoids, fully intact inside dry exobiology habitat facing closed steel door.';s['reference_brief']='SCN-007-exobiology-v003 identity. No two-eyed ghost. New interior frame before dissolution.'
 if name=='SMOKE-B':s['choreography']='Lavender vapor with amber/turquoise organoid sparks emerges and reforms the SAME ONE-EYED land-octopus Cyclops mantle and arms outside; steel door stays shut.';s['reference_brief']='Exterior reverse angle, faint gaseous wisp only at start. Match cyclops identity during emergence.'
 d['shots'].append(dict(id=s['id'],start_frame=s['start_frame'],end_frame_exclusive=s['end_frame_exclusive'],source=s['source'],source_in_frame=0,media_type='image',status='starting_frame_for_review',note=s['choreography'],direction_record='shots/SCN-011-six-shot-proposal.json',prompt_record='shots/SCN-011-starting-frame-prompts.json'))
proposal['status']='six_starting_frames_built_for_review';proposal['smoke_creature']='Established space-octopus Cyclops, user-selected';(r/'shots/SCN-011-six-shot-proposal.json').write_text(json.dumps(proposal,indent=2)+'\n')
d['current_preview']=preview;d['next_scene_planning'].update(preview=preview,status='six_starting_frames_for_review',smoke_creature='space-octopus Cyclops');p.write_text(json.dumps(d,indent=2)+'\n')
p=r/'shots/SCN-011-transformations-shot-plan.md';s=p.read_text(encoding='utf-8');s=s.replace('No new images or footage generated. Existing three-shot animatic remains current until discussion. All six starting images must be rebuilt; old anchors are inspiration only.','Six new starting frames built in v78; no footage generated. All six are now in animatic for review. Old anchors retained only as inspiration.').replace('Solid/coherent body interpretation needs review; old ghost still is mood/identity inspiration only.','Use established space-octopus Cyclops: one oversized eye, lavender-opal body and luminous amber/turquoise organoids.').replace('Creature with familiar smoky-reference head/eyes and soft tendrils','Established land-octopus Cyclops with one oversized eye, luminous organoids and soft arms');s+='\n\nV78: user selected space-octopus Cyclops for neuro-magical smoke ability. Six starting frames SCN-011-{SHRINK-A,SHRINK-B,GROW-A,GROW-B,SMOKE-A,SMOKE-B}-v001.png. Exterior smoke corrected from solid tentacle to airy vapor. Review starts only before paid animation; exact prompts in SCN-011-starting-frame-prompts.json.\n';p.write_text(s,encoding='utf-8')
p=r/'animatic/frame-review-current.json';t=p.with_suffix('.tmp');t.write_text(json.dumps(dict(video=str(r/preview),master_start=1)));t.replace(p)
p=Path('projects/monsters-loose/README.md');s=p.read_text(encoding='utf-8').replace('Current preview: **v77**','Current preview: **v78**').replace('recovery/animatic/MonstersLoose-v77-containment-storyboard.blend','recovery/animatic/MonstersLoose-v78-transformation-starts.blend').replace('Open the current v77 Blender','Open the current v78 Blender');p.write_text('Latest v78: six new Scene11 starting frames integrated at proposed cuts3379/3425/3515/3551/3642/3724, ending3775 exclusive. Full-size/tiny reptile, interior growth/exterior pre-breach insect, intact space-octopus Cyclops/interior and faint smoke at exterior keyhole. Large facility-scale enclosures. Built-in ImageGen; no Kling credits. Review3379.\n\n'+s,encoding='utf-8')
