from pathlib import Path
import json
r=Path('C:/audio/shared/amtw-runtime/jobs/monsters-loose-word-timing-20260913');p=r/'shots/shotlist.json';d=json.loads(p.read_text());preview='animatic/MonstersLoose-v77-containment-storyboard.mp4'
for s in d['shots']:
 if s['id'].startswith('SCN-010'):s.update(status='user_approved',approval_note='User approved completed v76 sequence: Perfect.')
for id,a,b,asset,note in [('SCN-011-SHRINK',3379,3515,'ANCH-011-A-v001.png','Tiny green reptile slips between bars; size-change staging and creature assignment provisional.'),('SCN-011-GROW',3515,3642,'ANCH-011-B-v001.png','Insect creature grows beyond enclosure; reference design and scale choreography provisional.'),('SCN-011-SMOKE',3642,3775,'ANCH-011-C-v001.png','Creature becomes smoke and passes through steel-door keyhole; design and transformation provisional.')]:
 if not any(s['id']==id for s in d['shots']):d['shots'].append(dict(id=id,start_frame=a,end_frame_exclusive=b,source='assets/'+asset,source_in_frame=0,media_type='image',status='storyboard_for_shot_planning',note=note))
d['scene10_production']=dict(d['next_scene_planning'],status='user_approved');d['next_scene_planning']=dict(scene='SCN-011',start_frame=3379,end_frame_exclusive=3775,duration_frames=396,preview=preview,status='storyboard_for_shot_planning',credits=0);d['current_preview']=preview;p.write_text(json.dumps(d,indent=2)+'\n')
p=r/'animatic/frame-review-current.json';t=p.with_suffix('.tmp');t.write_text(json.dumps(dict(video=str(r/preview),master_start=1)));t.replace(p)
p=Path('projects/monsters-loose/README.md');s=p.read_text(encoding='utf-8').replace('Current preview: **v76**, through master frame3378','Current preview: **v77**, through master frame3774').replace('recovery/animatic/MonstersLoose-v76-stealth-exit.blend','recovery/animatic/MonstersLoose-v77-containment-storyboard.blend').replace('Open the current v76 Blender','Open the current v77 Blender');p.write_text('Latest v77: user approved Scene10 v76. Extended animatic through Scene11 containment failures3379..3775 exclusive,396frames /16.5seconds. Three existing storyboard anchors: shrinking3379..3515, growing3515..3642, smoke/keyhole3642..3775. Designs/ability assignments remain provisional for discussion. No generation credits. Review3350 for lead-in.\n\n'+s,encoding='utf-8')
