from pathlib import Path
import json
r=Path('C:/audio/shared/amtw-runtime/jobs/monsters-loose-word-timing-20260913');p=r/'shots/shotlist.json';d=json.loads(p.read_text());preview='animatic/MonstersLoose-v91-swamp-meeting.mp4'
for s in d['shots']:
 if s['id']=='SCN-014-BEYOND-FENCE':s.update(source='motion-graphics/SCENE14-MEETING-001/meeting-timed-v001.mp4',media_type='video',status='generated_for_review',generation_record='video-tests/KLING-SCENE14-MEETING-001/request.json',effects_record='motion-graphics/SCENE14-MEETING-001/selections.json',direction_record='shots/SCN-014-swamp-meeting-direction.md',note='Approved starting frame; cautious social approach, warning air-snap/recoil and renewed approach.10second Kling3 take80credits,172frame edit; inspect review/selections for actual action.')
d['current_preview']=preview;d['ending_planning'].update(preview=preview,status='swamp_meeting_generated_for_review',credits_consumed=80);d['next_scene_planning']['preview']=preview;p.write_text(json.dumps(d,indent=2)+'\n')
p=Path('projects/monsters-loose/README.md');s=p.read_text(encoding='utf-8').replace('Current preview: **v90**','Current preview: **v91**').replace('recovery/animatic/MonstersLoose-v90-familiar-faces-procession.blend','recovery/animatic/MonstersLoose-v91-swamp-meeting.blend').replace('Open the current v90 Blender','Open the current v91 Blender');p.write_text('Latest v91: swamp-cousin meeting4242..4413,10second Kling3 take80credits edited into172frames. Remaining outro storyboard retained; next work crosscuts visitors/scientists/Harper/kid with swamp progression. Review4234.\n\n'+s,encoding='utf-8')
p=Path('projects/monsters-loose/HANDOFF.md');p.write_text('# Current working state\n\nv91 swamp-cousin meeting generated for review4242..4413,80credits. Earlier corridor procession approved. Later outro remains storyboard; next develop crosscuts with visitors, scientists, Harper and kid amid swamp procession. No further outro generation started. Deferred earlier fixes unchanged.\n')
p=r/'animatic/frame-review-current.json';t=p.with_suffix('.tmp');t.write_text(json.dumps(dict(video=str(r/preview),master_start=1)));t.replace(p)
