from pathlib import Path
import json
r=Path('C:/audio/shared/amtw-runtime/jobs/monsters-loose-word-timing-20260913');p=r/'shots/shotlist.json';d=json.loads(p.read_text());preview='animatic/MonstersLoose-v89-through-ending.mp4'
for s in d['shots']:
 if s['id']=='SCN-013-REMAINING-PROCESSION':s.update(status='starting_frame_user_approved',approval_note='User: Yep, this is good. Crane video remains ungenerated.')
d['shots']=[s for s in d['shots'] if not s['id'].startswith(('SCN-014-','SCN-015-'))]+json.loads((r/'animatic/ending-storyboard-records.json').read_text())
d['current_preview']=preview;d['next_scene_planning'].update(preview=preview,status='scene13_start_approved_video_pending_ending_storyboards_exposed');d['ending_planning']={'scenes':[14,15],'start_frame':4242,'end_frame_exclusive':5291,'duration_frames':1049,'status':'existing_storyboards_for_context_review','preview':preview};p.write_text(json.dumps(d,indent=2)+'\n')
p=Path('projects/monsters-loose/README.md');s=p.read_text(encoding='utf-8').replace('Current preview: **v88**','Current preview: **v89**').replace('recovery/animatic/MonstersLoose-v88-remaining-creatures.blend','recovery/animatic/MonstersLoose-v89-through-ending.blend').replace('Open the current v88 Blender','Open the current v89 Blender');p.write_text('Latest v89: extended existing storyboard through scenes14 and15 and full ending, last frame5290. New context4242..5290,43.708seconds. Scene13 starting frame approved; crane animation pending. No new generation credits. Review4242.\n\n'+s,encoding='utf-8')
p=Path('projects/monsters-loose/HANDOFF.md');p.write_text('# Current working state\n\nv89 exposes the full ending through5290. Scene14 beyond fence4242..4950; scene15 loose at last4951..5290. These are existing storyboard placeholders, for planning in context, not new generated video. Scene13 pig/Cyclops/bat starting frame approved; gentle crane take not yet generated. Scene12 procession approved. Deferred fixes: Harper cutesy response, earlier kid eye-roll. No credits spent for this extension.\n')
p=r/'animatic/frame-review-current.json';t=p.with_suffix('.tmp');t.write_text(json.dumps(dict(video=str(r/preview),master_start=1)));t.replace(p)
