from pathlib import Path
import json
r=Path('C:/audio/shared/amtw-runtime/jobs/monsters-loose-word-timing-20260913');p=r/'shots/shotlist.json';d=json.loads(p.read_text());preview='animatic/MonstersLoose-v87-gate-procession.mp4'
for s in d['shots']:
 if s['id']=='SCN-012-ESCAPE-SHOW':
  s.update(source='motion-graphics/SCENE12-PROCESSION-001/procession-timed-v001.mp4',media_type='video',status='single_take_for_review',starting_images=['assets/SCN-012-PROCESSION-v002.png'],generation_record='video-tests/KLING-SCENE12-PROCESSION-001/request.json',effects_record='motion-graphics/SCENE12-PROCESSION-001/selections.json',note='Single continuous procession replaces proposed two-angle cut. M.U.C.F. banners restored with master logo reference. Three visitors stand at left; lizard and insect move toward gate.12second take,96credits. Close visitor starting frame rejected for geographic/eyeline continuity; retained as unused alternate.')
d['current_preview']=preview;d['scene12_production'].update(status='exchange_placeholder_and_procession_for_review',preview=preview,credits_consumed=216);d['next_scene_planning']['preview']=preview;p.write_text(json.dumps(d,indent=2)+'\n')
p=Path('projects/monsters-loose/README.md');s=p.read_text(encoding='utf-8').replace('Current preview: **v86**','Current preview: **v87**').replace('recovery/animatic/MonstersLoose-v86-familiar-faces-storyboard.blend','recovery/animatic/MonstersLoose-v87-gate-procession.blend').replace('Open the current v86 Blender','Open the current v87 Blender');p.write_text('Latest v87: single continuous gate procession3883..4125, restored M.U.C.F. banners, three visitors and two escaping creatures.12second Kling take96credits. Review from3883; following familiar-face shots remain storyboard.\n\n'+s,encoding='utf-8')
p=Path('projects/monsters-loose/HANDOFF.md');p.write_text('# Current working state\n\nv87: continuous procession3883..4125 generated for review after user rejected close visitor angle/geography. Correct M.U.C.F. branding restored from BRAND001.12second silent Kling3 take96credits; Scene12 total216credits. Following familiar-face shots4126..4241 remain storyboard. Harper acting and earlier kid eye-roll remain deferred improvements. Media external; see inventory.\n')
p=r/'animatic/frame-review-current.json';t=p.with_suffix('.tmp');t.write_text(json.dumps(dict(video=str(r/preview),master_start=1)));t.replace(p)
