from pathlib import Path
import json
r=Path('C:/audio/shared/amtw-runtime/jobs/monsters-loose-word-timing-20260913');p=r/'shots/shotlist.json';d=json.loads(p.read_text());preview='animatic/MonstersLoose-v79-transformations.mp4';sel=json.loads((r/'motion-graphics/SCENE11-TRANSFORMS-001/selections.json').read_text())
for s in d['shots']:
 if s['id'].startswith('SCN-011'):
  name=s['id'].replace('SCN-011-','').lower();a=sel[name];s.update(source=a['output'],media_type='video',status='generated_assembled_for_review',effects_record='motion-graphics/SCENE11-TRANSFORMS-001/selections.json',generation_record=a['source'].rsplit('/',1)[0]+'/request.json',note=a['note'])
  if name=='smoke-b':s['review_concern']='Emergent Cyclops has correct single eye/organoids but smooth cartoon design rather than reference ink texture and proportions; user review needed.'
d['current_preview']=preview;d['next_scene_planning'].update(preview=preview,status='six_takes_assembled_for_review',credits=240,review_concern='Smoke-B creature design simplifies; assess before approval.');p.write_text(json.dumps(d,indent=2)+'\n')
p=r/'animatic/frame-review-current.json';t=p.with_suffix('.tmp');t.write_text(json.dumps(dict(video=str(r/preview),master_start=1)));t.replace(p)
p=Path('projects/monsters-loose/README.md');s=p.read_text(encoding='utf-8').replace('Current preview: **v78**','Current preview: **v79**').replace('recovery/animatic/MonstersLoose-v78-transformation-starts.blend','recovery/animatic/MonstersLoose-v79-transformations.blend').replace('Open the current v78 Blender','Open the current v79 Blender');p.write_text('Latest v79: six5second Kling takes assembled3379..3775 exclusive,240credits total. Shrink/escape, growth/breach, Cyclops smoke/keyhole emergence. Exact source maps: recovery/motion-graphics/SCENE11-TRANSFORMS-001/selections.json. Review concern: emerging Cyclops becomes smoother/cartoon-like, despite correct single eye/organoids. No paid retakes submitted. User approved all six starting frames. Review3379.\n\n'+s,encoding='utf-8')
p=r/'shots/SCN-011-transformations-shot-plan.md';p.write_text(p.read_text(encoding='utf-8')+'\n\n## v79 generated assembly\nAll six starting frames user approved. Six5second Kling v3 takes,40credits each240total, assembled to six planned intervals. One initial GROW-A upload was rate-limited before submission, then uploaded successfully; no duplicate generation. Source mappings in motion-graphics/SCENE11-TRANSFORMS-001/selections.json. SMOKE-B design drift toward smooth cartoon shape is flagged for user review. No automatic paid retake.\n',encoding='utf-8')
