from pathlib import Path
import json
r=Path('C:/audio/shared/amtw-runtime/jobs/monsters-loose-word-timing-20260913');p=r/'shots/shotlist.json';d=json.loads(p.read_text());preview='animatic/MonstersLoose-v88-remaining-creatures.mp4'
for s in d['shots']:
 if s['id']=='SCN-012-ESCAPE-SHOW':s.update(status='user_approved',approval_note='User: that shot actually is quite good.')
d['scene13_previous_storyboards']=[s for s in d['shots'] if s['id'].startswith('SCN-013-')]
d['shots']=[s for s in d['shots'] if not s['id'].startswith('SCN-013-')]+[dict(id='SCN-013-REMAINING-PROCESSION',start_frame=4126,end_frame_exclusive=4242,source='assets/SCN-013-PROCESSION-v001.png',source_in_frame=0,media_type='image',status='starting_frame_for_review',direction_record='shots/SCN-013-procession-direction.md',prompt_record='shots/SCN-013-procession-prompt.txt',note='Armored pig-reptile leads Cyclops and flying plesiosaur bat; AIR sign and single-eyed UNUSUAL. Gentle crane proposed; no video yet.')]
d['current_preview']=preview;d['next_scene_planning'].update(preview=preview,status='revised_procession_starting_frame_for_review',direction_record='shots/SCN-013-procession-direction.md');p.write_text(json.dumps(d,indent=2)+'\n')
p=Path('projects/monsters-loose/README.md');s=p.read_text(encoding='utf-8').replace('Current preview: **v87**','Current preview: **v88**').replace('recovery/animatic/MonstersLoose-v87-gate-procession.blend','recovery/animatic/MonstersLoose-v88-remaining-creatures.blend').replace('Open the current v87 Blender','Open the current v88 Blender');p.write_text('Latest v88: revised Scene13 single starting frame4126..4241. Pig-reptile leads Cyclops/bat beside corrected AIR and one-eyed UNUSUAL sign. Gentle crane proposed; no Kling submitted. Previous gate procession approved. Review4110.\n\n'+s,encoding='utf-8')
p=Path('projects/monsters-loose/HANDOFF.md');p.write_text('# Current working state\n\nv88: Scene13 remaining-creature procession starting frame for review4126..4241, corrected sign and referenced pig-reptile/Cyclops/bat. Gentle crane proposed; bat must flap. No Scene13 video generated yet. Previous two-creature gate procession approved. Next scene14 begins4242 beyond the fence. Deferred improvements remain Harper cutesy acting and earlier kid eye roll.\n')
p=r/'animatic/frame-review-current.json';t=p.with_suffix('.tmp');t.write_text(json.dumps(dict(video=str(r/preview),master_start=1)));t.replace(p)
