from pathlib import Path
import json
r=Path('C:/audio/shared/amtw-runtime/jobs/monsters-loose-word-timing-20260913');p=r/'shots/shotlist.json';d=json.loads(p.read_text());preview='animatic/MonstersLoose-v75-gate-release.mp4'
for s in d['shots']:
 if s['id']=='SCN-010-UNLOCK-ZOO':s.update(source='motion-graphics/SCENE10-GATE-001/gate-timed-v001.mp4',media_type='video',status='user_approved_take_assembled',approval_note='User: changed his grip and made it work just the way the switch should; this is perfect.',effects_record='motion-graphics/SCENE10-GATE-001/selections.json',note='Approved regrip and pull, held stop then initial gate opening;78frames3301..3379. First exit shot remains storyboard.')
d['current_preview']=preview;d['next_scene_planning'].update(preview=preview,status='approved_gate_take_assembled_exit_storyboard');d['next_scene_planning']['generation_test']['status']='user_approved_assembled';p.write_text(json.dumps(d,indent=2)+'\n')
p=r/'video-tests/KLING-SCENE10-GATE-001/review.json';a=json.loads(p.read_text());a['status']='user_approved_assembled';a['approval_note']='User approved grip change and mechanical action as perfect.';a['assembly']='motion-graphics/SCENE10-GATE-001/selections.json';p.write_text(json.dumps(a,indent=2))
p=r/'animatic/frame-review-current.json';t=p.with_suffix('.tmp');t.write_text(json.dumps(dict(video=str(r/preview),master_start=1)));t.replace(p)
p=Path('projects/monsters-loose/README.md');s=p.read_text(encoding='utf-8').replace('Current preview: **v74**','Current preview: **v75**').replace('recovery/animatic/MonstersLoose-v74-closed-gates-pull-lever.blend','recovery/animatic/MonstersLoose-v75-gate-release.blend').replace('Open the current v74 Blender','Open the current v75 Blender');p.write_text('Latest v75: user approved gate take001 as perfect. Assembled3301..3379 using78frame retime with full regrip/pull and initial opening. Exit3223..3301 remains A-v003 storyboard. No new generation credits. Review3280. Selections: recovery/motion-graphics/SCENE10-GATE-001/selections.json.\n\n'+s,encoding='utf-8')
