from pathlib import Path
import json
r=Path('C:/audio/shared/amtw-runtime/jobs/monsters-loose-word-timing-20260913');p=r/'shots/shotlist.json';d=json.loads(p.read_text());preview='animatic/MonstersLoose-v85-no-way-yes-way.mp4'
for s in d['shots']:
 if s['id']=='SCN-012-EXCHANGE':
  s.update(source='motion-graphics/SCENE12-EXCHANGE-001/exchange-composite-v001.mp4',media_type='video',status='generated_for_review',note='Two five-second native-dialogue takes edited into108frames. Referenced kid close-up, eight-frame blur pullback, Harper medium two-shot. Expanding Blender speech balloons on song word timing; generated dialogue excluded from master mix.',effects_record='motion-graphics/SCENE12-EXCHANGE-001/selections.json',generation_records=['video-tests/KLING-SCENE12-NO-001/request.json','video-tests/KLING-SCENE12-YES-001/request.json'],starting_images=['assets/SCN-012-NO-v001.png','assets/SCN-012-YES-v001.png'])
d['current_preview']=preview;d['next_scene_planning'].update(preview=preview,status='exchange_generated_for_review_escape_show_still_storyboard',credits_consumed=120)
p.write_text(json.dumps(d,indent=2)+'\n')
p=Path('projects/monsters-loose/README.md');s=p.read_text(encoding='utf-8').replace('Current preview: **v84**','Current preview: **v85**').replace('recovery/animatic/MonstersLoose-v84-next-scene-storyboard.blend','recovery/animatic/MonstersLoose-v85-no-way-yes-way.blend').replace('Open the current v84 Blender','Open the current v85 Blender');p.write_text('Latest v85: generated kid No way / Harper Yes way exchange3775..3882, eight-frame blur pullback and word-inflating Blender speech bubbles. Two five-second Kling3 native-dialogue1080p takes,120credits total. Original song audio preserved. Crowd/escape3883..4125 remains storyboard. Review3765.\n\n'+s,encoding='utf-8')
p=Path('projects/monsters-loose/HANDOFF.md');p.write_text('# Current working state\n\nv85: No way / Yes way exchange generated and assembled for user review, frames3775..3882; next escape-show shot3883..4125 remains storyboard. Two five-second Kling3 takes with native dialogue cost120credits. Original song is master audio. Approved scenes through11 unchanged. Defer earlier kid eye-roll and cleanup until the rest is fleshed out. Media external; see inventory.json.\n')
p=r/'animatic/frame-review-current.json';t=p.with_suffix('.tmp');t.write_text(json.dumps(dict(video=str(r/preview),master_start=1)));t.replace(p)
