from pathlib import Path
import json
r=Path('C:/audio/shared/amtw-runtime/jobs/monsters-loose-word-timing-20260913');p=r/'shots/shotlist.json';d=json.loads(p.read_text());preview='animatic/MonstersLoose-v90-familiar-faces-procession.mp4'
for s in d['shots']:
 if s['id']=='SCN-013-REMAINING-PROCESSION':s.update(source='motion-graphics/SCENE13-PROCESSION-001/procession-timed-v001.mp4',media_type='video',status='generated_for_review',starting_image='assets/SCN-013-PROCESSION-v001.png',generation_record='video-tests/KLING-SCENE13-PROCESSION-001/request.json',effects_record='motion-graphics/SCENE13-PROCESSION-001/selections.json',note='Seven-second Kling3 take selected into116frames,56credits; gentle rising camera, pig-reptile/Cyclops/bat procession beside corrected sign. Review pending.')
d['current_preview']=preview;d['next_scene_planning'].update(preview=preview,status='scene13_generated_for_review',credits_consumed=56);d['ending_planning'].update(preview=preview,status='replanning_swamp_procession_and_reaction_crosscuts',direction_record='shots/SCN-014-015-outro-revision.md');p.write_text(json.dumps(d,indent=2)+'\n')
p=Path('projects/monsters-loose/README.md');s=p.read_text(encoding='utf-8').replace('Current preview: **v89**','Current preview: **v90**').replace('recovery/animatic/MonstersLoose-v89-through-ending.blend','recovery/animatic/MonstersLoose-v90-familiar-faces-procession.blend').replace('Open the current v89 Blender','Open the current v90 Blender');p.write_text('Latest v90: generated Scene13 procession4126..4241,7second Kling3 take56credits. Outro remains storyboard through5290; next direction is swamp procession crosscut with visitors/scientists/Harper/kid. Review4110.\n\n'+s,encoding='utf-8')
p=Path('projects/monsters-loose/HANDOFF.md');p.write_text('# Current working state\n\nv90: Scene13 referenced procession generated for review4126..4241 (7second Kling3 take,56credits). Full ending storyboard remains through5290. Next: regenerate odd-looking swamp setup, continue procession outside, crosscut final40seconds with visitors, scientists, Harper and kid to create more activity. Do not treat current outro storyboard holds as final shot plan. Deferred earlier fixes unchanged.\n')
p=r/'animatic/frame-review-current.json';t=p.with_suffix('.tmp');t.write_text(json.dumps(dict(video=str(r/preview),master_start=1)));t.replace(p)
