import json
from pathlib import Path

r=Path(__file__).resolve().parent.parent
lock='STYLE AND CONTINUITY LOCK: Preserve the supplied illustration identities, proportions, clothing, coherent anatomy, ink outlines, fine crosshatching, stable paper texture, teal night and amber highlights throughout. One continuous shot, no cuts, no morphing, no new text or speech bubbles, no lip-sync or audible dialogue. Keep all established subjects recognizable and in frame. No humans transform into monsters. Motion is natural within the illustrated world.'
specs=[
 ('CEO',4414,4465,4,'After 0.5 seconds of quiet breathing, the woman studies an impressive creature offscreen RIGHT. Her gaze briefly travels from its height down to its body and back, one eyebrow lifts slightly, then her chin rises a little in cool calculating approval. Keep expression controlled, lips closed, portfolio steady; no laughter, talking, giant grin or grand gesture. Readable appraisal during seconds 0.5 to 2.5, then hold with breathing. Fixed camera.'),
 ('APPRAISE',4465,4495,3,'After a half-second lead-in the green reptile boss looks at someone offscreen LEFT, makes one small inquisitive head cant, then narrows one eye slightly as if appraising her in return. A dry curious expression, closed mouth, no roar or attack. Perform the tilt during 0.5 to 1.5 seconds and hold while breathing. Fixed camera.'),
 ('POLITICIAN',4495,4538,3,'First half-second quiet lead-in. The man gives his lapels one small simultaneous downward straightening tug, draws his shoulders back and lifts his chest and chin in a self-important display toward offscreen RIGHT. Complete the single gesture by 2 seconds. Keep face composed and mouth closed, no winking, speech, laughter or broad grin. Hands remain separate and anatomically correct. Fixed camera.'),
 ('DISPLAY',4538,4568,3,'First half-second quiet lead-in. The armored pig-reptile raises its head and broad chest in one proud territorial display, looking offscreen LEFT, a small matching gesture to a pompous man. Keep four feet grounded, stocky body and horns identical, no bipedal transformation, charging, mouth roar or new spikes. Complete rise by 1.5 seconds, then hold alert with a small breath. Fixed camera.'),
 ('SCIENTISTS',4568,4624,4,'First half-second quiet lead-in. Both scientists observe their escaped creations beyond the window with restrained proprietary pride. The senior woman subtly lifts her chin and turns her eyes toward the male scientist; he gives one small satisfied nod while still studying the animals outside. Their pleased expressions are faintly unsettling, lips closed, no comedy, talking or waving. All principal action within 0.5 to 2.8 seconds, then breathe. Keep hands stable and natural. Fixed camera.'),
 ('PLAY',4624,4719,6,'First half-second quiet lead-in. These exact two swamp reptiles cautiously play-test each other. During 0.5 to 1.7 seconds the green orange-spined boss leans its snout toward the mossy cousin across the gap. During 1.7 to 2.6 the cousin makes one brief feint forward WITHOUT touching or biting, boss immediately draws his head back and shifts weight. During 2.6 to 4.3 both soften and lean cautiously back toward each other, heads tilted, a readable near miss and renewed curiosity. Final seconds gentle breathing and water ripples. Preserve who is where, log/reeds and coherent limbs. No injury, collision, tongues, kissing, grappling, second creature morph or violent fight. Locked camera.'),
 ('INSPECTOR',4719,4793,5,'First half-second quiet lead-in. Inspector holds her clipboard then stops writing, slowly lowers clipboard from chest toward waist during 0.5 to 2.3 seconds as she watches offscreen RIGHT. Skepticism gives way to quiet astonished fascination, eyes open slightly and corners of mouth soften. A small forward lean at 2.5 seconds; then watch, breathe and blink. Keep pencil in hand, real fingers, no speech, exaggerated grin or head wobble. Fixed camera.'),
 ('HARPER-KID',4793,4951,8,'First half-second quiet lead-in. Harper initially watches the departing monsters offscreen RIGHT while the boy already looks up at her. At 1 to 2.8 seconds she gradually turns her head and eyes down toward the boy and gives one restrained reassuring small smile. He meets her gaze with quiet delighted disbelief, a tiny eyebrow lift and small smile, hugging his sketchbook. At 3.5 to 5.5 seconds they turn their attention back toward the creatures offscreen RIGHT together. Remaining seconds watch the departures, breathe naturally, slight hair movement. Harper is a grounded professional, never cutesy or coy: no wink, giggle, exaggerated head tilt, hand flourish or bobbing. Lips closed, no speech, no touching. Camera imperceptibly eases backward, only 3 percent wider across whole take.'),
 ('FINALE',4951,5291,15,'A fifteen-second uninterrupted final tableau. First half-second quiet lead-in. Green reptile boss remains comfortably draped over fallen log on LEFT, satisfied and relaxed; tiny bronze insect stays perched RIGHT foreground and slowly sweeps its feather antennae. 0.5 to 3 seconds: subtle breathing, slow contented blink, small settling of foreclaw on log. 3 to 5 seconds: concentric ripples form in open midground water RIGHT, boss notices and slowly turns head toward them without leaving log. 5 to 8 seconds: one separate friendly long-necked aquatic reptile rises gradually from water in the midground, head first then curved neck and a low dark green back; wet skin, small yellow eye, graceful plesiosaur-like neck, no wings, no duplicate boss. It remains well behind and separate from the foreground tail/insect. Modest rings and drips, no spectacular splash. Boss watches with calm recognition, a subtly pleased expression. 8 to 11 seconds: aquatic resident settles floating, boss relaxes again and turns his face partway back toward us with a satisfied look, stays on log. 11 to 15 seconds: peaceful breathing, antenna motion, slow swimming ripple and hanging moss. Camera nearly fixed for first 6 seconds, then a very gentle crane upward and backward, ending only about 12 percent wider while keeping boss prominent. No forced final pose or cut, no rapid camera move, no transition to another setting, no text. The insect never grows or flies away. No new foreground creatures; only one aquatic resident emerges.'),
]
plans=[]
for name,start,end,seconds,direction in specs:
 stem=('SCN-015-' if name=='FINALE' else 'SCN-014-')+name
 image='assets/'+stem+'-v001.png'
 prompt=lock+'\n'+direction
 folder=r/'video-tests'/('KLING-SCENE14-'+name+'-001');folder.mkdir(exist_ok=True)
 args=['image_to_video','--image',str(r/image),'--model','kling-video-v3_0','--duration',str(seconds),'--resolution','1080p','--imageCount','1','--enable_audio','false','--prefer_multi_shots','false',prompt]
 (folder/'request.json').write_text(json.dumps(dict(cli_args=args,expected_credits=seconds*8,purpose='User-approved reprise/outro plan, 12-frame lead-in and best-part selection.'),indent=2)+'\n')
 plans.append(dict(id=stem,name=name,start_frame=start,end_frame_exclusive=end,duration_frames=end-start,starting_image=image,generation_seconds=seconds,expected_credits=seconds*8,pre_roll_frames=12,post_roll_frames=8 if name=='FINALE' else 12,default_source_in_frame=12,generation_record=str((folder/'request.json').relative_to(r)).replace('\\','/'),prompt=prompt))
(r/'shots/SCN-014-015-production-plan.json').write_text(json.dumps(dict(fps=24,prompt_lock=lock,shots=plans,expected_credits=sum(x['expected_credits'] for x in plans),finale_handle_note='15-second model maximum: retain normal 12-frame lead-in, 340-frame edit and at least 8 frames tail. No end reference frame.'),indent=2)+'\n')
p=r/'shots/shotlist.json';d=json.loads(p.read_text())
if 'outro_previous_storyboards' not in d:
 d['outro_previous_storyboards']=[s for s in d['shots'] if s['start_frame']>=4414]
 d['shots']=[s for s in d['shots'] if s['start_frame']<4414]
 for s in plans:
  d['shots'].append(dict(id=s['id'],start_frame=s['start_frame'],end_frame_exclusive=s['end_frame_exclusive'],source=s['starting_image'],source_in_frame=0,media_type='image',status='generation_planned_user_authorized',generation_record=s['generation_record'],direction_record='shots/SCN-014-015-production-plan.json'))
for s in d['shots']:
 if s['id']=='SCN-014-BEYOND-FENCE':s['status']='user_approved'
d['ending_planning'].update(status='outro_generations_authorized',direction_record='shots/SCN-014-015-production-plan.json',planned_additional_credits=sum(x['expected_credits'] for x in plans))
p.write_text(json.dumps(d,indent=2)+'\n')
print('Prepared',len(plans),'shots;',sum(x['expected_credits'] for x in plans),'estimated credits')
