import json
from pathlib import Path
r=Path(__file__).resolve().parent.parent;p=r/'video-tests/KLING-SCENE14-FINALE-003';p.mkdir(exist_ok=True)
lock=json.loads((r/'shots/SCN-014-015-production-plan.json').read_text())['prompt_lock']
prompt=lock+'''
FIFTEEN SECONDS. Animate this exact composition as ONE unbroken shot. The green orange-spined boss stays draped on the SAME log LEFT for the ENTIRE video; its torso, hips and hands remain resting on that log, it never stands up, climbs down or moves to another place. The bronze insect remains perched on the SAME branch RIGHT. The moss-covered cousin is already visible as a partly submerged broad head in the RIGHT MIDGROUND; animate THAT exact head rising with its own short-necked shoulders from that water location. No new character design, no long neck.
0-0.5 seconds: quiet natural lead-in. 0.5-3seconds: boss breathes contentedly and slowly blinks, head relaxed. Cousin's eyes and upper snout remain at water surface with faint ripples. 3-7seconds: cousin slowly rises vertically until its broad mossy shoulders and upper chest clear the water, short natural neck, wet moss hanging and dripping, exactly the same wide amphibian-reptile face and large amber eyes as visible at start. One slender long-fingered hand may gently disturb the water beside its own body. Keep cousin in the same midground water location behind the insect, no touching, no sudden pop, no long neck or second monster. During the rise, boss only turns its head toward the cousin while keeping body sprawled on the log. 7-10seconds: they look at each other quietly, cousin blinks and remains half-submerged. 10-15seconds: boss rests its chin more comfortably on log with satisfied eyes, while cousin and insect make only tiny breathing and antenna motions. Peaceful conclusion, no chase, no jump, no fight.
Camera makes a smooth slow CRANE UP AND BACK throughout, very slight at first, clearer after3seconds, ending about25percent wider and visibly higher. Reveal more water and surrounding foliage while keeping the SAME moon, distant facility, log, branches and all three creatures in continuous spatial relationship. Stable horizon; no orbit or sideways camera reversal. No dissolve, cut, change of scene, sudden jump, inserted reference image or transformation. Keep the detailed ink hatching and mottled textures on every creature, no cartoon simplification. Dark teal night, amber reflections, unchanged facility geometry. Keep distant red lamps in place for post-production blinking.'''
args=['image_to_video','--image',str(r/'assets/SCN-015-FINALE-v002.png'),'--model','kling-video-v3_0','--duration','15','--resolution','1080p','--imageCount','1','--enable_audio','false','--prefer_multi_shots','false',prompt]
(p/'request.json').write_text(json.dumps(dict(cli_args=args,expected_credits=120,purpose='Correct take002 reference-scene contamination: revised starting composition anchors swamp cousin already at waterline, no external Element or end frame.',pre_roll_frames=12,post_roll_frames=8,master_start=4951,master_end_exclusive=5291),indent=2)+'\n')
(r/'video-tests/KLING-SCENE14-FINALE-002/review.json').write_text(json.dumps(dict(status='rejected',reason='Character identity improves but shot transitions into reference encounter scene and loses resting log tableau; not assembled.',credits=120),indent=2))
(r/'video-tests/run-finale3.py').write_text((r/'video-tests/run-scene14.py').read_text().replace("+'-001'","+'-003'"))
finish=(r/'video-tests/finish-finale2.py').read_text().replace('FINALE-002','FINALE-003').replace('OUTRO-002','OUTRO-003').replace('v002','v003').replace("+'-002'","+'-003'").replace('review-finale2','review-finale3')
(r/'video-tests/finish-finale3.py').write_text(finish)
