import json,subprocess
from pathlib import Path
root=Path(r'C:\audio\shared\amtw-runtime\jobs\monsters-loose-word-timing-20260913')
out=root/'video-tests'/'KLING-POV-001';out.mkdir(exist_ok=True)
if (out/'submission.json').exists():raise SystemExit('Existing submission; do not resubmit')
prompt='''One continuous eight-second subjective point-of-view shot through the eyes of an unseen DOG-SIZED animal slinking away under cover inside this zoo. Camera eye height stays about 40-50 cm above the soil. MOST IMPORTANT: THE CAMERA STAYS INSIDE THE SHADOWY PLANTING BED BEHIND FOLIAGE FOR THE ENTIRE SHOT. Travel along the concealed soil strip parallel to the walkway, never across the curb, never onto the open paved concourse. The open path is only glimpsed sideways through leaves. Keep multiple nearby leaves and stems framing and partially shielding the view at every moment; new foliage replaces passing foliage, no final emergence into an open view.
+Already moving cautiously from the first frame. Seconds 0-3: slow purposeful low forward slink under leaves, slight natural animal head sway but very little bounce, nearby fronds passing close to camera with clear parallax. Seconds 3-4: ease almost to a stop under cover and make a small watchful glance toward the lit path through a gap, still inside the planting bed. Seconds 4-8: turn attention back along the sheltered route and creep forward a little faster, remaining concealed behind overlapping foliage, continuing motion through the final frame. This is a furtive animal sneaking away, not a smooth sightseeing drone, running chase or camera zoom. Keep horizon stable and camera low.
+Preserve enclosure 4 and coherent cream concrete, black mesh doors, warm amber lamps, cool teal night and distant laboratory from the source. Door 2 and Harper remain entirely out of view. All gates stay closed in this view. No person or creature appears. NEVER show observer paws, claws, ears, limbs, body, shadow or reflection. No visible monster, no giant viewpoint, no rising camera, no transition, no text, no speed lines or thought bubbles. Preserve original graphic-novel bold ink, crosshatching and restrained halftone; no photorealistic conversion. No audio.'''.replace('\n+','\n')
(out/'prompt.txt').write_text(prompt)
timing={'clip_id':'KLING-POV-001','fps':24,'requested_duration_seconds':8,'assumed_pre_roll_frames':12,'assumed_pre_roll_seconds':.5,'minimum_assumed_post_roll_frames':12,'provisional_master_in_frame':380,'master_out_frame_exclusive':504,'source_zero_master_frame':368,'source_zero_master_seconds':367/24,'planned_source_in_frame':12,'planned_source_out_frame_exclusive':136,'planned_tail_frames':56,'actual_source_in_frame':None,'actual_source_out_frame_exclusive':None,'status':'submitted','note':'Provisional beat 11.1 insert after Oh my, before sign shot. Generous eight-second source for selection. Confirm trim after review; preserve original assumptions.'}
(out/'timing.json').write_text(json.dumps(timing,indent=2))
args=['image_to_video','--image',str(root/'assets'/'SCN-002-stealth-pov-in-v002.png'),'--model','kling-video-v3_0','--duration','8','--resolution','1080p','--imageCount','1','--enable_audio','false','--prefer_multi_shots','false',prompt]
(out/'request.json').write_text(json.dumps({'expected_credits':64,'cli_args':args},indent=2))
(out/'submission.json').write_text('{"local_status":"submission_started"}')
r=subprocess.run(['C:/Program Files/nodejs/node.exe','C:/Users/arneg/AppData/Roaming/npm/node_modules/@klingai/cli-global/dist/cli.js',*args],capture_output=True,text=True,encoding='utf-8')
(out/'submission.json').write_text(r.stdout);(out/'submission-stderr.txt').write_text(r.stderr);print(r.stdout)
