import json,subprocess
from pathlib import Path
root=Path(r'C:\audio\shared\amtw-runtime\jobs\monsters-loose-word-timing-20260913')
out=root/'video-tests'/'KLING-SIGN-002';out.mkdir(exist_ok=True)
if (out/'submission.json').exists():raise SystemExit('Existing submission; do not resubmit')
prompt='One continuous six-second graphic-novel shot. Camera completely locked. Harper faces the viewer with a cheerful theatrical expression and performs the sung phrase "Got the hang of every face you made" with CLEAR ACTIVE SINGING MOUTH SHAPES, moving lips and jaw visibly, not a closed-mouth smile. First 1.4 seconds: a small inviting presentation gesture toward the sign and a preparatory breath. Seconds1.4-4.8: she sings with distinct open and closed mouth shapes and expressive eyebrows, her face mostly frontal and clearly visible; gently turns her open presenting palm upward. Last1.2 seconds: finish singing and settle into a knowing smile. Keep head movement small for subsequent recorded-vocal lip sync. Preserve her identity, red curls, olive uniform, anatomy and coiled rope.\nThe beast stays DEEP INSIDE the enclosure, at least two metres behind the closed wire-mesh front wall. Its dark silhouette shifts slowly a short distance parallel to the REAR wall, with small shoulder and head movement. ALL front fence posts and diamond mesh remain continuously visible IN FRONT OF and occluding the creature at every moment. The mesh is a solid unbroken foreground barrier: no body part crosses its plane, no head protrudes, no leaning toward the fence, no entrance or exit, no opening gate. Keep creature size constant and shadowy, a distant dark shape behind the mesh rather than a foreground head. Gentle amber lamp flicker and tiny leaf movement add life.\nPreserve enclosure number4, rigid cage geometry, closed gate, exact sign and icons, moonlit teal night and amber lamps. Same bold ink contours, crosshatching and halftone, no photorealistic conversion. No new creatures or people, captions, bubbles, chains or motion lines. No camera movement, zoom, cuts or generated audio.'
(out/'prompt.txt').write_text(prompt,encoding='utf-8')
timing={'clip_id':'KLING-SIGN-002','fps':24,'requested_duration_seconds':6,'assumed_pre_roll_frames':12,'assumed_pre_roll_seconds':.5,'minimum_assumed_post_roll_frames':12,'provisional_master_in_frame':504,'source_zero_master_frame':492,'source_zero_master_seconds':491/24,'planned_source_in_frame':12,'actual_source_in_frame':None,'actual_source_out_frame_exclusive':None,'lyric_master_start_seconds':21.865816,'lyric_master_end_seconds':25.179816,'status':'submitted_base_motion','note':'Base performance for subsequent recorded-vocal lip sync. Final cut and next shot boundary pending review; does not replace full original 15s sign anchor.'}
(out/'timing.json').write_text(json.dumps(timing,indent=2))
args=['image_to_video','--image',str(root/'assets'/'SCN-003-sign-presentation-clean-v001.png'),'--model','kling-video-v3_0','--duration','6','--resolution','1080p','--imageCount','1','--enable_audio','false','--prefer_multi_shots','false',prompt]
(out/'request.json').write_text(json.dumps({'expected_credits':48,'cli_args':args},indent=2))
(out/'submission.json').write_text('{"local_status":"submission_started"}')
r=subprocess.run(['C:/Program Files/nodejs/node.exe','C:/Users/arneg/AppData/Roaming/npm/node_modules/@klingai/cli-global/dist/cli.js',*args],capture_output=True,text=True,encoding='utf-8')
(out/'submission.json').write_text(r.stdout);(out/'submission-stderr.txt').write_text(r.stderr);print(r.stdout)
