import json,subprocess
from pathlib import Path
root=Path(r'C:\audio\shared\amtw-runtime\jobs\monsters-loose-word-timing-20260913')
out=root/'video-tests'/'KLING-SIGN-001';out.mkdir(exist_ok=True)
if (out/'submission.json').exists():raise SystemExit('Existing submission; do not resubmit')
prompt='''One continuous six-second shot, preserving the supplied graphic-novel illustration. Locked camera and stable framing. Harper, the red-haired female zookeeper in the olive uniform, makes a small, elegant show-and-tell presentation of the creature sign with her open hand, with a knowing amused expression. She stays facing mostly toward the viewer, her face clearly visible and unobscured throughout, making restrained natural performance gestures suitable for adding sung lip-sync afterward. Her head stays reasonably steady; no profile turn. Begin with gentle motion already underway; do not hold a frozen first frame. Her presenting hand slowly sweeps toward the sign, then settles naturally. Do not point toward the camera or wave broadly. Preserve her hand anatomy, hair, clothes and coiled rope.
Behind the cage mesh, the existing large shadowy beast slowly shifts its weight and lumbers a small distance sideways during the middle of the shot, then settles. Its movement supplies a subtle ominous counterpoint to her cheerful presentation. The beast remains a dark indistinct silhouette entirely behind the mesh; never reveal a detailed face, teeth, skin or anatomy. No glowing eyes yet. Maintain the enclosure number 4, the exact sign layout and icons, the fencing, lamps and background architecture. Preserve bold ink contours, crosshatching, restrained halftone and teal moonlit night with amber lamps. No photorealistic conversion, no added chains, motion streaks, words, captions or bubbles. No new people or creatures. No cuts, no zoom or pullout, no camera movement, no generated audio.'''
(out/'prompt.txt').write_text(prompt,encoding='utf-8')
timing={'clip_id':'KLING-SIGN-001','fps':24,'requested_duration_seconds':6,'assumed_pre_roll_frames':12,'assumed_pre_roll_seconds':.5,'minimum_assumed_post_roll_frames':12,'provisional_master_in_frame':504,'source_zero_master_frame':492,'source_zero_master_seconds':491/24,'planned_source_in_frame':12,'actual_source_in_frame':None,'actual_source_out_frame_exclusive':None,'lyric_master_start_seconds':21.865816,'lyric_master_end_seconds':25.179816,'status':'submitted_base_motion','note':'Base performance for subsequent recorded-vocal lip sync. Final cut and next shot boundary pending review; does not replace full original 15s sign anchor.'}
(out/'timing.json').write_text(json.dumps(timing,indent=2))
args=['image_to_video','--image',str(root/'assets'/'SCN-003-sign-presentation-clean-v001.png'),'--model','kling-video-v3_0','--duration','6','--resolution','1080p','--imageCount','1','--enable_audio','false','--prefer_multi_shots','false',prompt]
(out/'request.json').write_text(json.dumps({'expected_credits':48,'cli_args':args},indent=2))
(out/'submission.json').write_text('{"local_status":"submission_started"}')
r=subprocess.run(['C:/Program Files/nodejs/node.exe','C:/Users/arneg/AppData/Roaming/npm/node_modules/@klingai/cli-global/dist/cli.js',*args],capture_output=True,text=True,encoding='utf-8')
(out/'submission.json').write_text(r.stdout);(out/'submission-stderr.txt').write_text(r.stderr);print(r.stdout)
