import json,subprocess
from pathlib import Path
root=Path(r'C:\audio\shared\amtw-runtime\jobs\monsters-loose-word-timing-20260913')
out=root/'video-tests'/'KLING-BOLT-001';out.mkdir(exist_ok=True)
if (out/'submission.json').exists():raise SystemExit('Existing submission; stopping')
prompt='''One continuous ten-second graphic-novel shot. The first image is the standing starting pose; the final image is the crouched resting pose. Lock the camera and environment. Harper smoothly lowers from standing into the exact end-image crouch within the FIRST 1.7 SECONDS: bend knees and hips naturally, settle one knee on the ground, brace one gloved hand on her raised knee and lower the other hand near the bolt without touching it. Keep both eyes directed at the oversized bolt throughout. Reach the end-reference crouched composition EARLY, by second 1.7, then remain in this crouch for the rest of the shot. Do NOT spread the descent across ten seconds. Seconds 1.7-10: a living quiet hold, subtle breathing, one natural blink and a tiny concerned eyebrow reaction around second 2.3, attentively inspecting the bolt. No speaking or singing. Keep head low looking at bolt; do not look at camera or stand back up. The bolt stays stationary on the paving and is never picked up. The gate remains slightly ajar and stationary. Preserve exact Harper identity, curly red hair, olive uniform, gloves, boots, badges, proportions and coherent anatomy. Preserve enclosure 2, single oversized bolt with no washer/nut, paving, amber lamps, teal night, lab and signs. Same bold graphic-novel ink, crosshatching, halftone and cream highlights. No camera movement, zoom, cuts, added people, creatures, extra hardware, motion lines, text or thought bubbles. A separate thought bubble will be composited later. Maintain subtle living motion through the end, no fade or freeze.'''
(out/'prompt.txt').write_text(prompt)
timing={'clip_id':'KLING-BOLT-001','fps':24,'requested_duration_seconds':10,'assumed_pre_roll_frames':12,'assumed_pre_roll_seconds':.5,'minimum_assumed_post_roll_frames':12,'master_in_frame':292,'master_out_frame_exclusive':504,'source_zero_master_frame':280,'source_zero_master_seconds':279/24,'planned_source_in_frame':12,'planned_source_out_frame_exclusive':224,'actual_source_in_frame':None,'actual_source_out_frame_exclusive':None,'oh_master_seconds':13.858816,'my_master_seconds':14.199816,'oh_source_seconds':13.858816-279/24,'my_source_seconds':14.199816-279/24,'target_crouch_reached_source_seconds':1.7,'lip_sync':False,'status':'submitted','note':'One-based master frames; zero-based source frames, exclusive out. Thought bubble added separately. AI action timing is a target, verify result.'}
(out/'timing.json').write_text(json.dumps(timing,indent=2))
args=['image_to_video','--image',str(root/'assets'/'SCN-002-bolt-standing-in-v001.png'),'--tailImage',str(root/'assets'/'SCN-002-bolt-inspection-v002.png'),'--model','kling-video-v3_0','--duration','10','--resolution','1080p','--imageCount','1','--enable_audio','false','--prefer_multi_shots','false',prompt]
(out/'request.json').write_text(json.dumps({'expected_credits':80,'cli_args':args},indent=2))
(out/'submission.json').write_text('{"local_status":"submission_started"}')
r=subprocess.run(['C:/Program Files/nodejs/node.exe','C:/Users/arneg/AppData/Roaming/npm/node_modules/@klingai/cli-global/dist/cli.js',*args],capture_output=True,text=True,encoding='utf-8')
(out/'submission.json').write_text(r.stdout);(out/'submission-stderr.txt').write_text(r.stderr);print(r.stdout)
