#!/usr/bin/env python3
"""
Machine-readable still-generation manifest for an outside generator
(Codex desktop + the OpenAI image API, or anything else that loops).

    python3 tools/still_manifest.py

Writes codex/stills_manifest.json (all paths relative to codex/, which is
the self-contained handoff folder: refs in, images out): one entry per setup with the fully
expanded still prompt (cast lines substituted, framing clause, lock block
appended -- byte-identical to the Still block in prompts/prompts.md), the
reference images to attach, the output file names, and the acceptance
guards. See codex/README.md for the procedure that consumes it.
"""
from __future__ import annotations

import collections
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from mvlib import ROOT, load  # noqa: E402
from prompts import expand, read_style  # noqa: E402

PLACEHOLDER = re.compile(r"\{\{\s*([\w-]+)\s*\}\}")

# which reference photographs an outside generator attaches, by content
LIKENESS = "refs/astronaut_likeness.jpg"      # the twins share one face
MERFOLK = "refs/merfolk_likeness_gpt.jpg"     # the approved chrome school
SPECIMEN = "refs/specimen_ref.jpg"            # the helical organism
WORLD = "refs/world_anchor.jpg"               # photographic anchor against illustration drift
SPECIMEN_SETUPS = {"canal_map_macro", "specimen_table_macro", "astronomer_desk_sync",
                   "astronaut_inspect_medium", "interference_bloom"}


def main():
    sl = load(ROOT / "shots" / "shotlist.json")
    lock, _refs, cast = read_style(ROOT / "shots" / "style.md")
    conventions = {k: v for k, v in load(ROOT / "shots" / "conventions.json").items()
                   if not k.startswith("_")}
    still_lock = re.sub(r"\s*Camera locked off.*?speed ramps\.", "", lock, flags=re.S)

    groups = collections.OrderedDict()
    for s in sl["shots"]:
        groups.setdefault(s.get("setup") or s["id"], []).append(s)

    entries = []
    for key, shots in groups.items():
        still = next((s["still"] for s in shots if s.get("still")), "")
        if not still:
            continue
        ids = next((s["conventions"] for s in shots if s.get("conventions")), [])
        phrases = [conventions[i]["still"] for i in ids if i in conventions and conventions[i].get("still")]
        framing = ("Framing: " + "; ".join(phrases) + ".") if phrases else ""
        prompt = " ".join(t for t in ("Film still. " + expand(still, cast, set()), framing) if t)
        prompt = prompt.strip() + "\n\n" + still_lock

        used = set(PLACEHOLDER.findall(still))
        refs = []
        if used & {"astronaut", "astronomer"}:
            refs.append(LIKENESS)
        if "merfolk" in used:
            refs.append(MERFOLK)
        if key in SPECIMEN_SETUPS:
            refs.append(SPECIMEN)
        if not refs:
            refs.append(WORLD)

        guards = ["no text, captions, titles or lettering anywhere in the frame",
                  "photographed, never illustrated: a 35mm three-strip Technicolor film still"]
        if used & {"astronaut", "astronomer"}:
            guards.append("her face must match the attached likeness photograph exactly; no eyewear")
        if "merfolk" in used:
            guards.append("every mer-folk has exactly one large round eye centered in the face, no second eye, "
                          "a fish tail below the waterline and no legs; all of them identical")
        if not (used & {"astronaut", "astronomer"}):
            guards.append("no people in frame" + (" except the mer-folk" if "merfolk" in used else ""))

        entries.append({
            "setup": key,
            "slate": next((s["description"] for s in shots if s.get("description")), ""),
            "sections": sorted({s["section"] for s in shots}),
            "cuts": [s["id"] for s in shots],
            "lyric": next((s["lyric"] for s in shots if s.get("lyric")), ""),
            "refs": refs,
            "prompt": prompt,
            "guards": guards,
            "outputs": [f"out/{key}_{v}.jpg" for v in ("a", "b")],
        })

    out = ROOT / "codex" / "stills_manifest.json"
    out.write_text(json.dumps({
        "_comment": "Generated by tools/still_manifest.py from shots/shotlist.json + shots/style.md + "
                    "shots/conventions.json. Do not edit by hand; edit the sources and re-run.",
        "image": {"size": "1536x1024", "aspect": "16:9 (crop 1536x1024 to 1536x864 centered if the API "
                  "cannot do 16:9 directly)", "quality": "high", "variants_per_setup": 2},
        "setups": entries,
    }, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {out}  —  {len(entries)} setups, "
          f"{sum(len(e['outputs']) for e in entries)} images")


if __name__ == "__main__":
    main()
